// playground/vue/src/App.vue
<script setup lang="ts">
import { shallowRef, onMounted, onUnmounted } from 'vue'
import { EffectsCtx } from 'webgl-effects'

import Filters from './Filters.vue'
import { createVideo } from '../../common/video'

const canvasRef = shallowRef<HTMLCanvasElement | null>(null)

const video = shallowRef<HTMLVideoElement>(createVideo())
const effectsCtx = shallowRef<EffectsCtx>()

video.value.requestVideoFrameCallback(function loop() {
  if (!effectsCtx.value) return

  effectsCtx.value.render(video.value)

  video.value.requestVideoFrameCallback(loop)
})

const init = () => {
  const canvas = canvasRef.value
  const videoEl = video.value

  if (!canvas || !videoEl) return

  const ctx = canvas.getContext('webgl')
  if (!ctx) {
    throw new Error('WebGL not supported')
  }

  effectsCtx.value = new EffectsCtx(ctx)
}

const cleanup = () => {
  if (video.value) {
    video.value.pause()
    video.value.src = ''
    video.value = null!
  }
}

onMounted(() => init())
onUnmounted(() => cleanup())
</script>

<template>
  <div class="app">
    <canvas ref="canvasRef" width="720" height="480"></canvas>

    <Filters :effectsCtx />
  </div>
</template>

// playground/react/src/App.tsx
import './App.css'

import { useRef, useState, useEffect } from 'react'
import { EffectsCtx } from 'webgl-effects'

import { Filfers } from './Filters'
import { useVideo } from './video'

const App = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [effectsCtx, setEffectsCtx] = useState<EffectsCtx | null>(null)

  const video = useVideo()

  useEffect(() => {
    if (!video || !effectsCtx) return

    video.requestVideoFrameCallback(function loop() {
      if (!video) return

      effectsCtx.render(video)
      video.requestVideoFrameCallback(loop)
    })
  }, [effectsCtx])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    const ctx = canvas.getContext('webgl')
    if (!ctx) {
      throw new Error('Failed to get WebGL context')
    }

    const effectsCtx = new EffectsCtx(ctx)
    setEffectsCtx(effectsCtx)

    return () => {
      effectsCtx.destroy()
    }
  }, [canvasRef.current])

  return (
    <div className="app">
      <canvas ref={canvasRef} width="720" height="480"></canvas>

      <Filfers effectsCtx={effectsCtx} />
    </div>
  )
}

export default App
