// playground/vue/src/Filters.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { EffectsCtx } from 'webgl-effects'

import { filters as _filters } from '../../common/filters'

interface Props {
  effectsCtx?: EffectsCtx
}
const { effectsCtx } = defineProps<Props>()

const filters = ref(
  _filters.map((filter) => ({
    ...filter,
    preset: { ...filter.filterClass.preset },
    active: false
  }))
)

function onClick(filter: (typeof filters.value)[number]) {
  if (!effectsCtx) {
    return
  }

  filter.active = !filter.active

  if (filter.active) {
    effectsCtx.filter.add(filter.filterClass)
    // TODO: Modify configuration through the form
    effectsCtx.filter.updateOptions(filter.filterClass, filter.preset)
  } else {
    effectsCtx.filter.remove(filter.filterClass)
  }
}
</script>

<template>
  <ul class="filters">
    <li v-for="filter in filters" :key="filter.label">
      <button
        class="filter-button"
        :class="{
          active: filter.active
        }"
        @click="onClick(filter)"
      >
        {{ filter.label }}
      </button>
    </li>
  </ul>
</template>

// playground/react/src/Filters.tsx
import { useState } from 'react'
import type { EffectsCtx } from 'webgl-effects'

import { filters } from '../../common/filters'

export const Filfers = ({ effectsCtx }: { effectsCtx: EffectsCtx | null }) => {
  if (!effectsCtx) {
    return null
  }

  const [filterState, setFilterState] = useState(
    filters.map((filter) => ({
      ...filter,
      preset: filter.filterClass.preset,
      active: false
    }))
  )

  const onClick = (clickedFilter: (typeof filters)[number]) => {
    setFilterState((prevFilters) =>
      prevFilters.map((filter) => {
        if (filter.filterClass !== clickedFilter.filterClass) {
          return filter
        }

        const newActive = !filter.active
        if (newActive) {
          effectsCtx.filter.add(filter.filterClass)
          // TODO: Modify configuration through the form
          effectsCtx.filter.updateOptions(filter.filterClass, filter.preset)
        } else {
          effectsCtx.filter.remove(filter.filterClass)
        }

        return { ...filter, active: newActive }
      })
    )
  }

  return (
    <ul className="filters">
      {filterState.map((filter, index) => (
        <li key={index}>
          <button
            className={filter.active ? 'filter-button active' : 'filter-button'}
            onClick={() => onClick(filter)}
          >
            {filter.label}
          </button>
        </li>
      ))}
    </ul>
  )
}
